[package]
name = "focus-org"
version = "0.1.0"
authors = ["Jeff Mickey <j@codemac.net>"]
edition = "2018"

[dependencies]
chrono = "0.4"
regex = "1"
lazy_static = "1"

[[bin]]
name = "focus-org"
path = "main.rs"
